python -m torch.distributed.launch --nproc_per_node=1 --master_port=12233 --use_env run_train.py \
--diff_steps 100 \
--lr 0.0001 \
--learning_steps 10 \
--save_interval 1 \
--seed 102 \
--noise_schedule sqrt \
--hidden_dim 24 \
--bsz 24 \
--dataset qqp \
--data_dir datasets/qt \
--vocab bert \
--seq_len 64 \
--schedule_sampler lossaware \
--notes test-qqp
